name: Security Scan

on:
  schedule:
    - cron: '0 0 * * 0' # Every Sunday at midnight
  pull_request:
    branches: [ "main" ]

jobs:
  npm-audit:
    name: NPM Audit
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [order-service, status-update-service, websocket-service, client]
        
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: '18'
          
      - name: Run NPM Audit
        working-directory: ${{ matrix.service == 'client' && './client' || format('./services/{0}', matrix.service) }}
        run: npm audit --audit-level=high

  trivy:
    name: Trivy Vulnerability Scanner
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build an image from Dockerfile
        run: |
          docker build -t tracknow/order-service:${{ github.sha }} ./services/order-service
          docker build -t tracknow/client:${{ github.sha }} ./client

      - name: Run Trivy vulnerability scanner on Order Service
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'tracknow/order-service:${{ github.sha }}'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'

      - name: Run Trivy vulnerability scanner on Client
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'tracknow/client:${{ github.sha }}'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
